on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'LLVM Repo Tag'
        required: true
        type: string

name: Build

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2

      - name: Build
        shell: cmd
        env:
          TAG: ${{ inputs.tag }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          git clone --config core.autocrlf=false --depth 1 --branch %TAG% https://github.com/llvm/llvm-project.git

          mkdir build
          cd build

          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%cd%\..\package" ../llvm-project/llvm
          cmake --build . --config Release

          if not exist ..\package mkdir ..\package
          cmake --build . --target install --config Release
      
      - name: Archive
        env:
          TAG: ${{ inputs.tag }}
        run: 7z a -tzip %TAG%-dev-win64.zip ./package/

#       - uses: actions/upload-artifact@v3
#         with:
#           name: ${{ inputs.tag }}-dev-win64
#           path: archive/
          
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{ inputs.tag }}-dev-win64.zip


